apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
  labels:
    name: nodejs-app
spec:
  replicas: 2
  selector:
    matchLabels:
      name: nodejs-app
  template:
    metadata:
      name: nodejs-app
      labels:
        name: nodejs-app
    spec:
      containers:
        - name: nodejs-app
          image: demonaizu/nodeapp-test:1.4
          ports:
            - containerPort: 3000
          env:
            - name: MYSQL_HOST 
              value: mysql-stateful-service
            - name: MYSQL_PORT 
              value: '3306'
            - name: MYSQL_USER
              value: root
            - name: MYSQL_ROOT_PASSWORD
              value: password
            - name: MYSQL_DATABASE
              value: nodecrud
            - name: APP_PORT
              value: '3000'

---

apiVersion: v1
kind: Service
metadata:
  name: nodejs-app-service
spec:
  type: NodePort
  selector:
    name: nodejs-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31110